// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'get_auditor.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Auditor _$AuditorFromJson(Map<String, dynamic> json) => Auditor(
      json['auditor_name'] as String,
      json['auditor_phone'] as String,
      json['auditor_email'] as String,
      json['id_proof'] as String,
      json['adddress_proof'] as String,
      json['auditor_status'] as String,
      json['auditor_role'] as String,
      json['hash_password'] as String,
      json['auth_key'] as String,
      json['direct_company'] as String,
      json['gcm_key'] as String,
      json['otp'] as String,
      json['iphone_key'] as String,
      json['mobile_type'] as String,
      json['business_select_business_type'] as String,
      json['business_business_name'] as String,
      json['business_office_street_address'] as String,
      json['business_office_address_line'] as String,
      json['business_city'] as String,
      json['business_state'] as String,
      json['business_pincode'] as String,
      json['business_registration_date'] as String,
      json['buisness_are_you_msme'] as String,
      json['personal_full_name'] as String,
      json['personal_mobile_no'] as String,
      json['personal_alternate_mobile_no'] as String,
      json['personal_email_id'] as String,
      json['personal_permanent_address_is_same_as_above'] as String,
      json['personal_current_address'] as String,
      json['personal_current_address_city'] as String,
      json['personal_current_address_line'] as String,
      json['personal_current_address_state'] as String,
      json['personal_current_address_pincode'] as String,
      json['personal_current_address_country'] as String,
      json['pan_date_of_birth'] as String,
      json['pan_no'] as String,
      json['aadhaar_no'] as String,
      json['account_type'] as String,
      json['bank_account_no'] as String,
      json['bank_name'] as String,
      json['ifsc_code'] as String,
      json['total_team_members'] as String,
      json['select_the_states'] as String,
    );

Map<String, dynamic> _$AuditorToJson(Auditor instance) => <String, dynamic>{
      'auditor_name': instance.auditor_name,
      'auditor_phone': instance.auditor_phone,
      'auditor_email': instance.auditor_email,
      'id_proof': instance.id_proof,
      'adddress_proof': instance.adddress_proof,
      'auditor_status': instance.auditor_status,
      'auditor_role': instance.auditor_role,
      'hash_password': instance.hash_password,
      'auth_key': instance.auth_key,
      'direct_company': instance.direct_company,
      'gcm_key': instance.gcm_key,
      'otp': instance.otp,
      'iphone_key': instance.iphone_key,
      'mobile_type': instance.mobile_type,
      'business_select_business_type': instance.business_select_business_type,
      'business_business_name': instance.business_business_name,
      'business_office_street_address': instance.business_office_street_address,
      'business_office_address_line': instance.business_office_address_line,
      'business_city': instance.business_city,
      'business_state': instance.business_state,
      'business_pincode': instance.business_pincode,
      'business_registration_date': instance.business_registration_date,
      'buisness_are_you_msme': instance.buisness_are_you_msme,
      'personal_full_name': instance.personal_full_name,
      'personal_mobile_no': instance.personal_mobile_no,
      'personal_alternate_mobile_no': instance.personal_alternate_mobile_no,
      'personal_email_id': instance.personal_email_id,
      'personal_permanent_address_is_same_as_above':
          instance.personal_permanent_address_is_same_as_above,
      'personal_current_address': instance.personal_current_address,
      'personal_current_address_city': instance.personal_current_address_city,
      'personal_current_address_line': instance.personal_current_address_line,
      'personal_current_address_state': instance.personal_current_address_state,
      'personal_current_address_pincode':
          instance.personal_current_address_pincode,
      'personal_current_address_country':
          instance.personal_current_address_country,
      'pan_date_of_birth': instance.pan_date_of_birth,
      'pan_no': instance.pan_no,
      'aadhaar_no': instance.aadhaar_no,
      'account_type': instance.account_type,
      'bank_account_no': instance.bank_account_no,
      'bank_name': instance.bank_name,
      'ifsc_code': instance.ifsc_code,
      'total_team_members': instance.total_team_members,
      'select_the_states': instance.select_the_states,
    };
